Redirect expire session
back4app/parse-dashboard pull request #238
Opened 2021-02-02 20:49 UTC by nataliaconde

2021-02-03 01:00 UTC, davimacedo requested changes

2021-02-03 01:00 UTC, davimacedo commented on src/lib/axios.js
> +  if (status === 200 && typeof data !== "object"){
Poderia explicar?

2021-02-03 12:44 UTC, nataliaconde commented on src/lib/ParseApp.js
> +    return Promise.resolve(fields);
Corrigido

2021-02-03 12:47 UTC, nataliaconde commented on src/lib/axios.js
> +  if (status === 200 && typeof data !== "object"){
Claro! Bom, o que acontece quando a sessão do usuário expira é que ele não retorna mais um objeto do banco e sim um arquivo em HTML (que é um redirect), entretanto, retorna como 200. O que eu fiz foi verificar se a sessão está realmente expirada nesses casos.

2021-02-04 03:53 UTC, davimacedo approved these changes

2021-02-04 03:53 UTC, davimacedo commented
@nataliaconde acho que agora eh testar em homolog e subir.

2021-02-16 18:16 UTC, merged