Set expiration date via dashboard on session class
back4app/parse-dashboard pull request #241
Opened 2021-04-12 10:50 UTC by sadakchap

preventing update for expiration date, as it is readOnly attribute

2021-04-12 21:37 UTC, davimacedo requested changes
Hi @sadakchap 

Please find a comment below. Also, it would be good to send the PR only with the change regarding this specific issue.

2021-04-12 21:37 UTC, davimacedo commented on src/dashboard/Data/Browser/BrowserTable.react.js
> +const READ_ONLY = [ 'objectId', 'createdAt', 'updatedAt', 'sessionToken', 'expiresAt' ];
We should only consider it read only in the Session Class, right? But I am afraid that it will consider it readonly even in a custom class.

2021-04-13 11:39 UTC, sadakchap commented on src/dashboard/Data/Browser/BrowserTable.react.js
> +const READ_ONLY = [ 'objectId', 'createdAt', 'updatedAt', 'sessionToken', 'expiresAt' ];
Ah right, It will make `expiresAt` readOnly across classes. So, we need to first check if it is Session class, then if it is expiresAt, then make it readOnly. Should I add this explicit check ?
I tried creating a readOnly field, I don't thats possible from dashboard.

2021-04-19 05:59 UTC, davimacedo approved these changes

2021-04-19 05:59 UTC, merged