Import does not work when a string field has a number beginning with 0
back4app/parse-dashboard pull request #244
Opened 2021-04-13 12:51 UTC by sadakchap

removed checkType param from csv

2021-04-19 05:56 UTC, davimacedo commented on src/lib/ParseApp.js
> -      checkType: true
I'm not sure that's a good idea. What happens if we import a number? Will it be imported as a number or as a text?

2021-04-19 11:43 UTC, sadakchap commented on src/lib/ParseApp.js
> -      checkType: true
when we remove this option, it turns off default column parser, which was parsing "05" to a number parser & converting it a number("05" -> 5). But, now it will also import number as text, which will now give ParseError something like "expected a number but got a string". And most importantly import will fail.

For this, maybe we can use [custom column parser](https://www.npmjs.com/package/csvtojson#custom-parsers-function). I think we will need to loop over csv columns & check with our schema, whether that column is string or number and format it accordingly. 

1. we can get all column headers

```js
csv()
.on('header',(header)=>{
    //header=> [username, age, age2,...]
})

```
2. create a column Parser
```js
const customColParser = {};
headers.forEach(headCol => {
     colParser[headCol] = function(item, head){
        // item => "03", 45
        // head => age, age2
        // here check type of column in the schema & format it accordingly 
       return item;
    }
})
```
3. pass our custom parser to csv
```js
 csv({ colParser: customColParser})
```

Please let me know if you have some other possible ways.

2021-04-19 18:30 UTC, sadakchap commented
@davimacedo, updated the pr, now using custom parser to parse the data from csv only if className is present. Please let me know if we need more changes.

2021-04-21 04:26 UTC, davimacedo requested changes

2021-04-21 04:26 UTC, davimacedo commented on src/lib/ParseApp.js
> +    let jsonArray = await csv({
Maybe we should move this to an else statement so we can avoid parsing the file twice.

2021-04-21 04:28 UTC, davimacedo commented on src/lib/ParseApp.js
> -      checkType: true
They we resolved this is pretty smart and should work well!

2021-04-22 11:07 UTC, sadakchap commented on src/lib/ParseApp.js
> +    let jsonArray = await csv({
ok

2021-04-22 19:24 UTC, davimacedo approved these changes

2021-04-22 19:24 UTC, merged