Change class name layout
back4app/parse-dashboard pull request #313
Opened 2021-07-09 11:00 UTC by fn-faisal

2021-07-09 20:58 UTC, davimacedo requested changes

2021-07-09 20:58 UTC, davimacedo commented on src/components/CategoryList/CategoryList.scss
> + @import 'stylesheets/globals.scss';
Could you please revert these layout changes?

2021-07-09 20:58 UTC, davimacedo commented on src/components/LoginForm/LoginForm.scss
> +  width: 300px;
Why?

2021-07-09 20:58 UTC, davimacedo commented on src/dashboard/Data/Browser/B4ABrowserToolbar.react.js
> +  // if (count !== undefined) {
Why did you change this logic? I believe the logic should be the same.

2021-07-09 20:58 UTC, davimacedo commented on src/dashboard/Data/Browser/B4ABrowserToolbar.react.js
> +      // section={relation ? `Relation <${relation.targetClassName}>` : `Class | ${details.join(' \u2022 ')}`}
Not sure if we can comment this lines. Try to click on a relation and see what happens.

2021-07-16 10:07 UTC, fn-faisal commented on src/components/CategoryList/CategoryList.scss
> + @import 'stylesheets/globals.scss';
The changes have been reverted for the scss file.

2021-07-16 10:44 UTC, fn-faisal commented on src/components/LoginForm/LoginForm.scss
> +  width: 300px;
When I added the styling to sidebar, I had to increase it's size from 300px to 350px.
Upon reverting these changes, I think I updated the LoginForm by mistake.

2021-07-16 11:11 UTC, fn-faisal commented on src/dashboard/Data/Browser/B4ABrowserToolbar.react.js
> +  // if (count !== undefined) {
The details had the read/write permissions text and it was causing issue with the layout. I've updated the logic to pass the "read and write permissions" via another variable. I've updated the details to exclude the class permissions text and this is how the details appear now. 

<img width="808" alt="Screenshot 2021-07-16 at 4 10 55 PM" src="https://user-images.githubusercontent.com/23558802/125938959-ffb41264-c874-4686-a9ec-0ce5695adb00.png">

2021-07-16 11:12 UTC, fn-faisal commented on src/dashboard/Data/Browser/B4ABrowserToolbar.react.js
> +      // section={relation ? `Relation <${relation.targetClassName}>` : `Class | ${details.join(' \u2022 ')}`}
I've reverted this.

2021-07-16 19:46 UTC, davimacedo approved these changes

2021-07-16 19:46 UTC, merged